### PR TITLE
TravisCI

### PR DESCRIPTION
**Pull request by Islast**
branch to address issue #16

### CODE REVIEW

**Comment by KirstieJane** [comment]
Ah - but maybe merge this first and then you can add it to travis! I’m going to approve the PR and you can merge when you’re ready

**Comment by KirstieJane** [comment]
Here's the link to see the [project status on TravisCI](https://travis-ci.org/Islast/BrainNetworksInPython) for @Islast's [fork of BrainNetworksInPython](https://github.com/Islast/BrainNetworksInPython/).

The error I see is:

```
pytest

The program 'pytest' is currently not installed. To run 'pytest' please ask your administrator to install the package 'python-logilab-common'
```

Dunno what's up....

**Comment by KirstieJane** [comment]
New error!

```
============================= test session starts ==============================

platform linux -- Python 3.3.6, pytest-2.9.2, py-1.4.31, pluggy-0.3.1

rootdir: /home/travis/build/WhitakerLab/BrainNetworksInPython, inifile: 

collected 0 items 

========================= no tests ran in 0.05 seconds =========================

The command "py.test" exited with 5.
```

But I don't think this is a problem: I don't think there *are* any tests, right?
See: https://docs.pytest.org/en/latest/usage.html

**Comment by KirstieJane** [comment]
@islast - I'm so sorry for taking over here - I'm sitting at Geneva airport and wanted an easy win :grinning:

But yaaaaay! It goes green! 



Everything's still approved, but I'll wait on you to merge in case you want to add an actual test (or put my test somewhere sensible?)

**Comment by Islast** [comment]
Go @KirstieJane !! 
I've got some real tests that I'll pull request later but for now I'm very excited to get Travis CI email that doesn't say "still failing". 
P.S., N.B. no need to apologise for taking over

**Pull request merged**
