### PR TITLE
Add gif to README.md

### PR DESCRIPTION
**Pull request by harshitjindal**
Fixes issue https://github.com/WhitakerLab/BrainNetworksInPython/issues/25

### CODE REVIEW

**Comment by KirstieJane** [comment]
The gif looks very low res here: https://giphy.com/gifs/xT9Iggnr78YyYVUh7W

But I’m on my phone, does it look better when rendered in the README?

**Comment by harshitjindal** [comment]
I resized it to be small on purpose. The issue stated it had to be put in-line with the first line, so I calculated the pixel count, turned out to be 45x45

**Comment by harshitjindal** [comment]
Also, the gif looks better in the markdown. A very high res gif would have made the performance suffer. Not everyone is on wifi to stream a 20mb gif

**Comment by KirstieJane** [comment]
@harshitjindal - it depends on what the point of the gif is. When I suggested the idea to @Islast I imagined the equivalent of an embeded youtube video in the top right corner of the README file. The point is to showcase what we can learn about the brain using these methods.

As @Islast said, she can fiddle around with the formatting if she wants to. I'm about to be offline for 10 days so I can always open a new issue when I come back.

**Comment by harshitjindal** [comment]
@KirstieJane I've tried changing the dimensions, and the quality yesterday, before pushing the changes, and this is what I found out to the best. Of course the formatting can be changed later, but as far as the size and quality of gif is concerned, this is what I think works out the best. If you're still unsure about it, feel free to discard. I did what the Issue #25 asked for :)

**Comment by Islast** [comment]
Thanks again for the pull request @harshitjindal :+1: 

I'm sorry I didn't get back to your question last night. We wanted it next to "Welcome to the BrainNetworksInPython GitHub repository!✨"
I think this is my first lesson in making issues for a wider audience, because I failed to explain the placement, and I neglected to mention the size I had in mind for the GIF. Not your fault at all @harshitjindal :star:.
If you wanted to make some more changes, I'd prefer to use [this GIF](https://j.gifs.com/wm9JYm.gif) for the readme. If not, go ahead and merge :smile:

**Comment by harshitjindal** [comment]
@Islast Are you sure I can merge it?
That's what I get. "Only those with write access to this repository can merge pull requests."
I don't see a merge button, like there usually is, and I'm unable to merge from my terminal also.
So, could you please squash my commits into one and merge?

I don't have any problem fixing the placement myself, let me know if you want me to. I was just thinking if a new issue could be created to fix the placement (for newcomers). Everyone wins that way :)

**Comment by Islast** [comment]
Yep, cool good idea :star:. You're right you don't have write access, my bad. merging

**Pull request merged**
