### PR TITLE
Catch non-numeric columns before correlating

### LINKED ISSUE #56: object dtype issue in scripts/make_corr_matrices.py
Just a note:
In the script scripts/make_corr_matrices.py, I have to modify the function `def create_corrmat(df, names, covars_list):` this line `M = df_res.loc[:, names].corr().values` into `M = df_res.loc[:, names].astype(float).corr().values`. In order to avoid `object` dtype error. 

Python 3.5.2 :: Anaconda 4.2.0 (64-bit)
numpy (1.11.1)
pandas (0.18.1)

### PR DESCRIPTION
**Pull request by Islast**
- [x] I'm ready to merge

* **What's the context for this pull request?** 
_(this is a good place to reference any issues that this PR addresses)_
#56 need to make sure create_corrmat is not correllating over strings. Following discussion, we have decided to raise a typeerror if a column of nonumeric values is presented. 

* **What's new?**
Changes to `make_corr_matrices`. We now have a function `get_non_numeric_cols` which returns a numpy arrray of the names of non-numeric columns. If this array is not empty the functions `create_corrmat` and `create_residuals_df` will now raise a TypeError

* **What should a reviewer feedback on?**
@KirstieJane tell me if you like the direction of the new changes

* **Does anything need to be updated after merge?** 
_(e.g the wiki or the WhitakerLab website)_
can close #56 
The documentation is already in the script, so when we get sphinx working this should be "auto"-documented

### CODE REVIEW

**Comment by KirstieJane** [comment]
Hey @Islast - this fix totally works, but I don’t like it very much. I think it would make more sense to ensure that they column in `df_res` is made as float rather than forcing this conversion here.

I’m on my phone so I’m not much help, but ping me on Gitter if you have any questions!

**Comment by KirstieJane** [comment]
https://github.com/Islast/BrainNetworksInPython/blob/7b4985b5cb6fc6d37c9866494cc7ac7896801d5c/scripts/make_corr_matrices.py#L32

I think it’s this line. If you make a column of 1s (so no covariates) does it make them as integers?

**Comment by Islast** [comment]
We don't get this dtype error in any of our unittests. I think the best solution is probably to check the dataframe when it comes in and throw up a dtype error. Then the user can do their own investigation into why their dataframe has non-numeric columns

**Comment by Islast** [comment]
The new commit raises an error if any columns in the data frame are of a non numeric dtype (these are the ones pandas.DataFrame.corr will ignore)

**Comment by Islast** [comment]
pinging @KirstieJane to remind her to check out the new changes :spaghetti:

**Pull request merged**
